server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: SafePay-Vault

  # Database 설정 (AWS RDS MySQL)
  datasource:
    url: jdbc:mysql://terraform-20260508075842560200000001.c18y4gs8uo61.ap-northeast-2.rds.amazonaws.com:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${RDS_PASSWORD:mysql1234}

  # JPA 및 Hibernate 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    open-in-view: false

  # Redis 설정 (JWT Refresh Token 및 캐시용)
  data:
    redis:
      host: localhost
      port: 6379

  #  OAuth2 설정 (구글 소셜 로그인)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            # 구글 로그인 후 돌아올 백엔드 경로
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

  # SQL 초기화 모드
  sql:
    init:
      mode: NEVER

#  JWT 커스텀 설정
jwt:
  # 보안을 위해 실제 운영 환경에서는 환경 변수를 사용
  secret: ${JWT_SECRET_KEY:your_default_secret_key_at_least_32_characters_long_for_security}
  access-token-expiration: 3600000 # 1시간
  refresh-token-expiration: 604800000 # 7일

# 로그 레벨 설정
logging:
  level:
    org.springframework.security: DEBUG
    mini_pjt3.com.team1: DEBUG
    # 쿼리 파라미터 로그 확인용
    org.hibernate.type.descriptor.sql: TRACE